name: Financial_Reporting
description: ''
version: 0.3-SNAPSHOT
author: anshuman@simpledatalabs.com
pipelines:
  pipelines/load_person_silver:
    name: load_person_silver
    description: ''
    author: anshuman@simpledatalabs.com
    mode: batch
    language: scala
    createdAt: '2022-05-08 10:35:57'
    datasets:
      inputs:
      - 4088/datasets/person_bronze
      outputs:
      - 4088/datasets/person_silver
    dependencies: {}
  pipelines/load_transactions:
    name: load_transactions_silver
    description: ''
    author: anshuman@simpledatalabs.com
    mode: batch
    language: scala
    createdAt: '2022-05-08 13:27:50'
    datasets:
      inputs:
      - 4088/datasets/transactions_bronze
      - 4088/datasets/acc_status_silver
      outputs:
      - 4088/datasets/transactions_silver
    dependencies: {}
  pipelines/aggregated_report_gold:
    name: aggregated_report_gold
    description: ''
    author: anshuman@simpledatalabs.com
    mode: batch
    language: scala
    createdAt: '2022-05-10 11:50:19'
    datasets:
      inputs: []
      outputs: []
    dependencies: {}
  pipelines/load_products:
    name: load_products_silver
    description: ''
    author: anshuman@simpledatalabs.com
    mode: batch
    language: scala
    createdAt: '2022-05-08 14:52:28'
    datasets:
      inputs:
      - 4088/datasets/products_bronze
      outputs:
      - 4088/datasets/products_silver
    dependencies: {}
  pipelines/load_acc_status_silver_scala:
    name: load_acc_status_silver
    description: ''
    author: anshuman@simpledatalabs.com
    mode: batch
    language: scala
    createdAt: '2022-05-07 11:06:37'
    datasets:
      inputs:
      - 4088/datasets/acc_status_bronze
      outputs:
      - 4088/datasets/acc_status_silver
    dependencies: {}
datasets:
  datasets/transactions_bronze:
    name: transactions_bronze
    description: ''
    author: anshuman@simpledatalabs.com
    createdAt: '2022-05-08 13:33:04'
    physicalDatasets:
      anshuman2:
        fabricId: 838
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-08 13:33:04'
  datasets/products_silver:
    name: products_silver
    description: ''
    author: anshuman@simpledatalabs.com
    createdAt: '2022-05-08 15:30:22'
    physicalDatasets:
      anshuman2:
        fabricId: 838
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-08 15:30:22'
  datasets/person_silver:
    name: person_silver
    description: ''
    author: anshuman@simpledatalabs.com
    createdAt: '2022-05-06 12:51:36'
    physicalDatasets:
      anshuman2:
        fabricId: 838
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-06 12:51:36'
  datasets/products_bronze:
    name: products_bronze
    description: ''
    author: anshuman@simpledatalabs.com
    createdAt: '2022-05-08 14:59:54'
    physicalDatasets:
      anshuman2:
        fabricId: 838
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-08 14:59:54'
  datasets/acc_status_bronze:
    name: acc_status_bronze
    description: ''
    author: anshuman@simpledatalabs.com
    createdAt: '2022-05-05 17:32:06'
    physicalDatasets:
      anshuman2:
        fabricId: 838
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-05 17:32:06'
      anshuman:
        fabricId: 811
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-07 11:07:27'
  datasets/transactions_silver:
    name: transactions_silver
    description: ''
    author: anshuman@simpledatalabs.com
    createdAt: '2022-05-08 14:08:42'
    physicalDatasets:
      anshuman2:
        fabricId: 838
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-08 14:08:42'
  datasets/acc_status_archive:
    name: acc_status_archive
    description: ''
    author: anshuman@simpledatalabs.com
    createdAt: '2022-05-05 17:51:55'
    physicalDatasets:
      anshuman2:
        fabricId: 838
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-05 17:51:55'
  datasets/acc_status_silver:
    name: acc_status_silver
    description: ''
    author: anshuman@simpledatalabs.com
    createdAt: '2022-05-05 17:38:40'
    physicalDatasets:
      anshuman2:
        fabricId: 838
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-05 17:38:40'
      anshuman:
        fabricId: 811
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-06 12:40:30'
  datasets/person_bronze:
    name: person_bronze
    description: ''
    author: anshuman@simpledatalabs.com
    createdAt: '2022-05-06 12:49:39'
    physicalDatasets:
      anshuman2:
        fabricId: 838
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-06 12:49:39'
      anshuman:
        fabricId: 811
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-08 10:38:45'
jobs:
  jobs/silver_loads2:
    name: silver_loads2
    description: ''
    fabricUID: 838
    scheduler:
      Databricks: {}
    jobSize: small
    scheduleCron: 0 0 0 1/1 * ? *
    timeout: null
    alerting:
      emails: anshuman@simpledatalabs.com
      onStart: true
      onSuccess: true
      onFailure: true
    pipelines:
    - 4088/pipelines/load_products
    - 4088/pipelines/load_person_silver
    - 4088/pipelines/load_acc_status_silver_scala
    - 4088/pipelines/load_transactions
    enabled: true
    createdAt: '2022-05-10 06:37:27'
    author: anshuman@simpledatalabs.com
  jobs/import_products:
    name: import_products
    description: ''
    fabricUID: null
    scheduler:
      Airflow: {}
    jobSize: Small
    scheduleCron: 0 0 0 1/1 * ? *
    timeout: null
    alerting:
      emails: anshuman@simpledatalabs.com
      onStart: true
      onSuccess: true
      onFailure: true
    pipelines:
    - 4088/pipelines/load_transactions
    - 4088/pipelines/load_acc_status_silver_scala
    - 4088/pipelines/load_person_silver
    - 4088/pipelines/load_products
    enabled: true
    createdAt: '2022-05-08 15:33:04'
    author: anshuman@simpledatalabs.com
  jobs/ttt:
    name: ttt
    description: ''
    fabricUID: null
    scheduler:
      Airflow: {}
    jobSize: null
    scheduleCron: null
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    enabled: null
    createdAt: '2022-05-10 05:35:56'
    author: anshuman@simpledatalabs.com
  jobs/test:
    name: test
    description: ''
    fabricUID: null
    scheduler:
      Airflow: {}
    jobSize: Small
    scheduleCron: 0 0 0 1/1 * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - 4088/pipelines/load_person_silver
    enabled: true
    createdAt: '2022-05-10 06:23:01'
    author: anshuman@simpledatalabs.com
  jobs/silver_loads:
    name: silver_loads
    description: ''
    fabricUID: null
    scheduler:
      Airflow: {}
    jobSize: null
    scheduleCron: null
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    enabled: null
    createdAt: '2022-05-10 05:16:39'
    author: anshuman@simpledatalabs.com
libraries: []
subgraphs: {}
dependencies: []
template: '[]'
